version: '2'
services:
  truffle-games:
    container_name: truffle-games
    #restart: always
    build: .
    working_dir: /code
    # command: ./truffle-init.sh
    #command: ng serve --host 0.0.0.0
    volumes:
      - .:/code
    ports:
      - '8080:8080'
    network_mode: "host"
